[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib", "lib/snekmate/src"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
vyper = { optimize = "gas" }
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
verbosity = 3
fuzz = { runs = 256, max_test_rejects = 65_536 }
invariant = { runs = 256, depth = 15 }

[vyper]
path = ".venv/bin/vyper"

[profile.ci]
force = true
verbosity = 4
fuzz = { runs = 10_000, max_test_rejects = 350_000 }
invariant = { runs = 375, depth = 500 }

[profile.echidna]
force = true
skip = ["src/**/*.vy"]
