name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: uv sync

      - name: Show the Vyper version
        run: uv run vyper --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Mamushi fmt
        run: uv run mamushi --check src/

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test --ffi -vvv
